### ISSUE TITLE
WS Consultar Perfiles del Sistema

### ISSUE THREAD

**Issue by yahercarrillo** [yahercarrillo/Softnnita#10]
EndPint : http://localhost:8080/ISoftProfile/GatewayServicesProfilersAndPermisions/consultarperfiles?llave_seguridad=eyJSRVFVRVNUIjoie1wiY2xpZW50ZUlTb2Z0XCI6XCJJU09GVFwiLFwiY2FuYWxcIjoxLFwiZmVjaGFJbmljaW9cIjpcIk9jdCAxLCAyMDE4IDEyOjAwOjAwIEFNXCIsXCJmZWNoYUZpblwiOlwiRGVjIDMxLCAyMDE4IDEyOjAwOjAwIEFNXCIsXCJpcFwiOlwiMTI3LjAuMC4xXCIsXCJ0aXBvTGljZW5jaWFcIjpcIk9QRU5fQUxMXCIsXCJkb2N0eXBlXCI6XCJEYXRvc0xpY2VuY2lhXCJ9IiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJJU09GVCJ9.qbc7qJA47PzLDCC3t6TGbZYNcmzACOlx7J0E3CvFNZc

Method : GET

**Comment by fcierra** [comment]
se valida el WS en mención quedando como pendiente: 

Cambiar la estructura de salida;

- "nombre" por "perfil"

**Comment by yahercarrillo** [comment]
Req - Release : 15de9bf

Output:

{
   "estatus": "INFO",
   "codigo": "200",
   "descripcion": "Proceso Efectivo de la operacion",
   "response":    [
            {
         "id": "2",
         "perfil": "COORDINADOR"
      },
            {
         "id": "6",
         "perfil": "GERENTE"
      },
            {
         "id": "4",
         "perfil": "GUEST"
      },
            {
         "id": "3",
         "perfil": "SUPERVISOR"
      }
   ]
}

**Comment by fcierra** [comment]
Se validan los siguientes ajustes:

- "nombre" por "perfil"

SE DA POR APROBADO EL WS EN MENCIÓN CERRANDO LOS INCIDENTES
