### ISSUE TITLE
WS Consultar Usuarios

### ISSUE THREAD

**Issue by fcierra** [yahercarrillo/Softnnita#2]
Estructura Entrada:
 - llave_seguridad

Estructura Salida:
 - nombres
 - apellidos
 - correo
 - estado
 - fecha_ultima_visita
 - sexo
 - login_usuario

**Comment by yahercarrillo** [comment]
Req Release : e3a218f
1,.) Se ajustan los parametros de entrada.
2.-)Se ajustan los parametros de salida.
3.-) Se ajustan los registros de bitacora dinamicos..

**Comment by yahercarrillo** [comment]
Req Release : 0a1b51b
1.-) Se recuperan los datos de correo y fecha de ultima visita.

**Comment by fcierra** [comment]
Se validan los ajustes realizados, quedando como pendiente lo siguiente:

- El formato de la fecha de ultima visita no es valido (examinar como esta en crear un usuario).
- Determinar que letra se utilizara para identificar el sexo de los usuarios "F" y "M", en la actualidad valida cualquier carácter.

**Comment by yahercarrillo** [comment]
Req - Release : b893a40

1.-) Se ajustan los sexos los cuales para el momento pueden solor ser un caracter : M,F,O.
2.-) Se ajustan los mensajes internazionalizables a los sexos.
3.-) Se agrega a la consulta de usuarios el campo sexo.
4.-) Se formatea la fecha al formato yyyy-MM-dd.

**Comment by fcierra** [comment]
Se validan los cambios efectuados:

1.-) Se ajustan los sexos los que para el momento pueden solor ser un caracter: M, F, O. 
2.-) Se ajustan los mensajes internazionalizables a los sexos. 
3.-) Se agrega a la consulta de usuarios del campo sexo. 
4.-) Se formatea la fecha al formato yyyy-MM-dd.

Se aprueba el WS Consultar Usuario quedando para posible integración.
