### ISSUE TITLE
WS Crear Usuario

### ISSUE THREAD

**Issue by fcierra** [yahercarrillo/Softnnita#4]

**Comment by fcierra** [comment]
Estructura entrada: 
- Cambiar loginname por usuario
- Cambiar email por correo
- Determinar longitud max de nombre, apellido, usuario de usuario (60)
- Determinar longitud min de nombre, apellido, usuario, correo de usuario, clave (5)
- Determinar longitud max de correo de usuario (60)
- Determinar longitud max de clave de usuario (15)
- Validar alfanumérico y caracteres especiales.
- Validar espacios en blanco.
- Validar mismo usuario pero con diferentes datos. 

Estructura salida : N/A

**Comment by yahercarrillo** [comment]
Release Bug : 6eac4b5

**Comment by yahercarrillo** [comment]
Body Entrada:

{
  "usuario":"yaher",
  "nombres":"Yaher Oscar",
  "apellidos":"Carrillo Domador",
  "correo":"yahercarrillo12@gmail.com",
  "clave":"Prueba12$"
}

**Comment by fcierra** [comment]
se validan los ajustes presentados, no se encuentran errores de pruebas según lo validado y estipulado.

**Comment by fcierra** [comment]
Validar que al crear un usuario, se pueda consultar previamente el perfil con el que fue creado, así se este sea por defecto.

**Comment by yahercarrillo** [comment]
Req - Release : 9dac4ef
1.-) Se agrega la asociacion del perfil al usuario.

**Comment by fcierra** [comment]
Se verifica los ajustes realizados (asociación del perfil al usuario.), quedando pendiente lo siguiente:

Por favor!

- Admitir la letra Ñ en nombres y apellidos.

**Comment by yahercarrillo** [comment]
Se verifica el incidente, se debe configurar la comunicacion UTF-8, como se muestra en la evidencia. Realizar esta operacion para todos los endpoint's.

![screenshot_1](https://user-images.githubusercontent.com/25934902/49960145-8658e380-fedd-11e8-9754-3538d44cf748.png)

**Comment by fcierra** [comment]
Se valida ajuste de poder escribir la letra "Ñ" ya sea en nombre o apellido, no se encuentra mas incidentes.

Se aprueba el WS Crear usuario. en MySql
