### ISSUE TITLE
WS Asociar Perfil a Usuario

### ISSUE THREAD

**Issue by yahercarrillo** [yahercarrillo/Softnnita#7]
- Asocia los perfiles indicados en parametros al usuario.
- Se validan los parametros de entrada.
- Se ajusta la semantica de entrada y salida a español.
- Se valida la licencia.
- Si el elemento no existe, se registra la transaccion y se notifica.
- Si se obtiene respuesta efectiva, sin detalles, significa que ya los elementos existian asociados para el usuario indicado.

EndPoint : http://localhost:8080/ISoftProfile/GatewayServicesUsersISoftProfile/asociarperfilusuario?llave_seguridad=eyJSRVFVRVNUIjoie1wiY2xpZW50ZUlTb2Z0XCI6XCJJU09GVFwiLFwiY2FuYWxcIjoxLFwiZmVjaGFJbmljaW9cIjpcIk9jdCAxLCAyMDE4IDEyOjAwOjAwIEFNXCIsXCJmZWNoYUZpblwiOlwiRGVjIDMxLCAyMDE4IDEyOjAwOjAwIEFNXCIsXCJpcFwiOlwiMTI3LjAuMC4xXCIsXCJ0aXBvTGljZW5jaWFcIjpcIk9QRU5fQUxMXCIsXCJkb2N0eXBlXCI6XCJEYXRvc0xpY2VuY2lhXCJ9IiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJJU09GVCJ9.qbc7qJA47PzLDCC3t6TGbZYNcmzACOlx7J0E3CvFNZc

Body:

{
  "usuario":"yaher",
  "perfiles":["SUPERVISOR1","OTRO"]
}

**Comment by fcierra** [comment]
Se validan los cambios y acciones efectuadas, quedando pendiente lo siguiente:

- No debe permitirme asociar un perfil a un usuario que esta en estado deshabilitado, actualmente si me permite esta asociación.
- Cambiar el mensaje cuando un usuario ya tiene agregado un perfil como; "Ya se encuentra asociado el perfil a este usuario", actualmente dice que "proceso efectivo en la operación".

Queda en discusión si el porque no me deja agregar un perfil administrador a un usuario.

**Comment by yahercarrillo** [comment]
Req - Release : 40d417f

- Se ajusta la validacion de un usuario deshabilitado, se agrega el mensaje internazionalizable.
- El segundo punto no se realiza, puesto que no es necesario mostrar el mensaje de que el usuario ya posee el perfil que intenta asociarse, en pro de dar la impresion de que se realiza la operacion, el mensaje informativo igual seria efectivo, puesto que es una validacion interna.

**Comment by fcierra** [comment]
Se validan los cambios efectuados "validación de un usuario deshabilitado" 

Se aprueba el WS asociar perfil usuario, quedando listo para posible integración.

**Comment by yahercarrillo** [comment]
Req - Release : 8741860
{
   "estatus": "INFO",
   "codigo": "200",
   "descripcion": "Proceso Efectivo de la operacion",
   "response":    [
            {
         "usuario": "YAHER",
         "nombres": "YAHER CARRILLO",
         "apellidos": "CARRILO DOMADOR",
         "perfil": "COORDINADOR",
         "estatus": "WARN",
         "codigo": "202",
         "descripcion": "No se agrega el perfil [COORDINADOR] al usuario [YAHER], ya que el perfil esta deshabilitado.    "
      },
            {
         "usuario": "YAHER",
         "nombres": "YAHER CARRILLO",
         "apellidos": "CARRILO DOMADOR",
         "perfil": "GERENTE",
         "estatus": "INFO",
         "codigo": "200",
         "descripcion": "Se agrega satisfactoriamente el perfil."
      }
   ]
}

**Comment by fcierra** [comment]
Se valida los siguientes cambios ejecutados:

Permitir dar espacios entre textos.
Si el perfil está deshabilitado no debe permitir agregar un usuario (es la misma validación que se hace con los usuarios).
también se valida que cuando el usuario esta deshabilitado no permita hacer una asociación de perfil.

QUEDA NUEVAMENTE  APROBADO ESTE WS A PESAR QUE YA SE ENCONTRABA CERRADO.
